[workspace]
members = ["Android/Vault448Native", "Vault448-Common"]

resolver = "2"


[workspace.dependencies]
once_cell = "1.18.0"
human_format = "1.0.3"
dir-meta = "0.5.2"
camino = "1.1.6"
smol = "2.0.0"
async-dup = "1.2.4"
