[package]
name = "vault448-native"
authors = ["448 ENGINEERING DESIGN DEVELOPERS <superuser@448.africa>"]
version = "0.2.0-alpha1"
edition = "2021"
license = "LicenseRef-BSL-1.1"
description = "Simple Secure Beautiful File Manager."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vault448_native"
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "1.75.3", default-features = false }
