[tasks.default]
clear = true
dependencies = ["check"]

[tasks.android_arm_release]
script = '''
echo -------- ANDROID_BUILD::armv7_armv8_x86_64 ---------
cargo ndk -t armeabi-v7a -t arm64-v8a -t x86_64 -o ../android/app/src/main/jniLibs build --release
'''
dependencies = ["flutter_bridge"]

[tasks.android_x86_64_release]
script = '''
echo -------- ANDROID_BUILD::x86_64 ---------
cargo ndk -t x86_64 -o ../android/app/src/main/jniLibs build --release
'''
dependencies = ["flutter_bridge"]


[tasks.flutter_bridge]
script = '''
echo -------- FLUTTER_RUST_BRIDGE ---------
flutter_rust_bridge_codegen --rust-input ./src/api.rs  --dart-output ../lib/bridge_generated.dart
'''
