[tasks.default]
clear = true
dependencies = ["check"]

[tasks.android_arm_release]
script = '''
echo -------- ANDROID_BUILD::armv7_armv8_x86_64 ---------
cargo ndk -t armeabi-v7a -t arm64-v8a -o ../app/src/main/jniLibs build --release
'''
watch = { }

[tasks.android_x86_64_release]
script = '''
echo -------- ANDROID_BUILD::x86_64 ---------
cargo ndk -t x86_64 -o ../app/src/main/jniLibs build --release
'''
